// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"context"
)

type Querier interface {
	// This query counts ALL users that match the search filter.
	// This is used to calculate the total number of pages.
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodo(ctx context.Context, arg DeleteTodoParams) error
	// This query fetches ALL users that match the search filter.
	// Sorting and pagination will be handled in the Go code.
	GetAllUsersFiltered(ctx context.Context, arg GetAllUsersFilteredParams) ([]User, error)
	GetTodoByID(ctx context.Context, id string) (Todo, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListTodosByUser(ctx context.Context, userID string) ([]Todo, error)
	UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
