// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo.sql

package data

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (id, user_id, task)
VALUES (?, ?, ?)
RETURNING id, user_id, task, completed, created_at, updated_at
`

type CreateTodoParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Task   string `json:"task"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.ID, arg.UserID, arg.Task)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Task,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = ? AND user_id = ?
`

type DeleteTodoParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, arg.ID, arg.UserID)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, user_id, task, completed, created_at, updated_at FROM todos
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTodoByID(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Task,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodosByUser = `-- name: ListTodosByUser :many
SELECT id, user_id, task, completed, created_at, updated_at FROM todos
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTodosByUser(ctx context.Context, userID string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Task,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoStatus = `-- name: UpdateTodoStatus :one
UPDATE todos
SET completed = ?
WHERE id = ? AND user_id = ?
RETURNING id, user_id, task, completed, created_at, updated_at
`

type UpdateTodoStatusParams struct {
	Completed bool   `json:"completed"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoStatus, arg.Completed, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Task,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
