// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package data

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE
    email LIKE ? OR ? = ''
`

type CountUsersParams struct {
	Email   string      `json:"email"`
	Column2 interface{} `json:"column_2"`
}

// This query counts ALL users that match the search filter.
// This is used to calculate the total number of pages.
func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, arg.Email, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash)
VALUES (?, ?, ?)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUsersFiltered = `-- name: GetAllUsersFiltered :many
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE
    -- The second '?' parameter is the same as the search query.
    -- If the search query is empty (''), the second part of the OR becomes TRUE,
    -- effectively returning all users.
    email LIKE ? OR ? = ''
`

type GetAllUsersFilteredParams struct {
	Email   string      `json:"email"`
	Column2 interface{} `json:"column_2"`
}

// This query fetches ALL users that match the search filter.
// Sorting and pagination will be handled in the Go code.
func (q *Queries) GetAllUsersFiltered(ctx context.Context, arg GetAllUsersFilteredParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersFiltered, arg.Email, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
